apiVersion: v1
kind: Service
metadata:
  name: php-myadmin
  labels:
    app: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_HOST
              valueFrom:
               configMapKeyRef:
                name: myconfigmap
                key: pma_host
            - name: PMA_USER
              valueFrom:
               configMapKeyRef:
                name: myconfigmap
                key: pma_user
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: root_password
          ports:
            - containerPort: 80
